// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl7K-O05l_mfDDf8jxocMZvP95ayZdHQ8',
    appId: '1:198296856371:web:059a98184d397774f50046',
    messagingSenderId: '198296856371',
    projectId: 'mynextbook-flutter',
    authDomain: 'mynextbook-flutter.firebaseapp.com',
    storageBucket: 'mynextbook-flutter.appspot.com',
    measurementId: 'G-EN19LGZYY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrtzzIbfNDwMEOvR-eSsbB0ZDjIvWvqPk',
    appId: '1:198296856371:android:a5b91ef9cac8066df50046',
    messagingSenderId: '198296856371',
    projectId: 'mynextbook-flutter',
    storageBucket: 'mynextbook-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl0E0IhYEYmZfPFeb9Wq5KRmLx7Xknhx4',
    appId: '1:198296856371:ios:d8e0f7ebf94e92caf50046',
    messagingSenderId: '198296856371',
    projectId: 'mynextbook-flutter',
    storageBucket: 'mynextbook-flutter.appspot.com',
    iosClientId: '198296856371-d6psvprjlkucj9j14763bi1puhhdiqu6.apps.googleusercontent.com',
    iosBundleId: 'com.lgmakerdevs.mynextbook.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl0E0IhYEYmZfPFeb9Wq5KRmLx7Xknhx4',
    appId: '1:198296856371:ios:7d134b40ca406c47f50046',
    messagingSenderId: '198296856371',
    projectId: 'mynextbook-flutter',
    storageBucket: 'mynextbook-flutter.appspot.com',
    iosClientId: '198296856371-qitlsrtf8m19s13u0jpr95hcf954lkvt.apps.googleusercontent.com',
    iosBundleId: 'com.lgmakerdevs.mynextbook',
  );
}
