// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'modules/data/local/model/book_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6502539104987658899),
      name: 'BookEntity',
      lastPropertyId: const IdUid(8, 1455688131779583603),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1235374370493314429),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 6842382393636226890),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4803933817787878228),
            name: 'subtitle',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8201795958403825129),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7003026908571531163),
            name: 'previewLink',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1727859014397178346),
            name: 'image',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1448180861258980302),
            name: 'userId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 1455688131779583603),
            name: 'uuid',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 6502539104987658899),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    BookEntity: EntityDefinition<BookEntity>(
        model: _entities[0],
        toOneRelations: (BookEntity object) => [],
        toManyRelations: (BookEntity object) => {},
        getId: (BookEntity object) => object.id,
        setId: (BookEntity object, int id) {
          object.id = id;
        },
        objectToFB: (BookEntity object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final subtitleOffset = fbb.writeString(object.subtitle);
          final descriptionOffset = fbb.writeString(object.description);
          final previewLinkOffset = object.previewLink == null
              ? null
              : fbb.writeString(object.previewLink!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          final userIdOffset = fbb.writeString(object.userId);
          final uuidOffset = fbb.writeString(object.uuid);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, subtitleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addOffset(4, previewLinkOffset);
          fbb.addOffset(5, imageOffset);
          fbb.addOffset(6, userIdOffset);
          fbb.addOffset(7, uuidOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = BookEntity(
              uuid: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, ''),
              title: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              subtitle: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              description: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              previewLink: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              image: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              userId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [BookEntity] entity fields to define ObjectBox queries.
class BookEntity_ {
  /// see [BookEntity.id]
  static final id =
      QueryIntegerProperty<BookEntity>(_entities[0].properties[0]);

  /// see [BookEntity.title]
  static final title =
      QueryStringProperty<BookEntity>(_entities[0].properties[1]);

  /// see [BookEntity.subtitle]
  static final subtitle =
      QueryStringProperty<BookEntity>(_entities[0].properties[2]);

  /// see [BookEntity.description]
  static final description =
      QueryStringProperty<BookEntity>(_entities[0].properties[3]);

  /// see [BookEntity.previewLink]
  static final previewLink =
      QueryStringProperty<BookEntity>(_entities[0].properties[4]);

  /// see [BookEntity.image]
  static final image =
      QueryStringProperty<BookEntity>(_entities[0].properties[5]);

  /// see [BookEntity.userId]
  static final userId =
      QueryStringProperty<BookEntity>(_entities[0].properties[6]);

  /// see [BookEntity.uuid]
  static final uuid =
      QueryStringProperty<BookEntity>(_entities[0].properties[7]);
}
